media:
  input: src/assets/images
  output: /src/assets/images

content:
  - name: site_content
    label: Contenu du Site
    type: file
    path: src/data/site-content.yml
    fields:
      - label: Informations du Site
        name: site
        type: object
        fields:
          - label: Titre
            name: title
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Description
            name: description
            type: object
            fields:
              - { label: Français, name: fr, type: text }
              - { label: Anglais, name: en, type: text }
          - label: Mots-clés
            name: keywords
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }

      - label: Navigation
        name: nav
        type: object
        fields:
          - label: Accueil
            name: home
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: À propos
            name: about
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Équipements
            name: amenities
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Emplacement
            name: location
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Disponibilités
            name: availability
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Contact
            name: contact
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }

      - label: Section Hero
        name: hero
        type: object
        fields:
          - label: Titre
            name: title
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Sous-titre
            name: subtitle
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Description
            name: description
            type: object
            fields:
              - { label: Français, name: fr, type: text }
              - { label: Anglais, name: en, type: text }
          - label: Appel à l'action
            name: cta
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }

      - label: Section À propos
        name: about
        type: object
        fields:
          - label: Titre
            name: title
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Sous-titre
            name: subtitle
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Description
            name: description
            type: object
            fields:
              - { label: Français, name: fr, type: text }
              - { label: Anglais, name: en, type: text }
          - label: Caractéristiques
            name: features
            type: object
            fields:
              - label: Construction écologique
                name: eco
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: Bois & Isolation
                name: wood
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: Phyto-épuration
                name: phyto
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: Permaculture
                name: permaculture
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: Biodiversité
                name: biodiversity
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }

      - label: Section Hébergement
        name: accommodation
        type: object
        fields:
          - label: Titre
            name: title
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Taille
            name: size
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Capacité
            name: capacity
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }

      - label: Section Équipements
        name: amenities
        type: object
        fields:
          - label: Titre
            name: title
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Confort
            name: comfort
            type: object
            fields:
              - label: Titre
                name: title
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: Chauffage
                name: heating
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: Climatisation
                name: ac
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: WiFi
                name: wifi
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }
              - label: Livres
                name: books
                type: object
                fields:
                  - { label: Français, name: fr, type: string }
                  - { label: Anglais, name: en, type: string }

      - label: Section Emplacement
        name: location
        type: object
        fields:
          - label: Titre
            name: title
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Sous-titre
            name: subtitle
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Description
            name: description
            type: object
            fields:
              - { label: Français, name: fr, type: text }
              - { label: Anglais, name: en, type: text }

      - label: Section Contact
        name: contact
        type: object
        fields:
          - label: Titre
            name: title
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Sous-titre
            name: subtitle
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Téléphone (label)
            name: phone
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Numéro de téléphone
            name: phone_number
            type: string
          - label: Email (label)
            name: email
            type: object
            fields:
              - { label: Français, name: fr, type: string }
              - { label: Anglais, name: en, type: string }
          - label: Adresse email
            name: email_address
            type: string

  - name: site_images
    label: Images du Site
    type: file
    path: src/data/images.yml
    fields:
      - label: Section Hero
        name: hero
        type: object
        fields:
          - { label: Image principale, name: main, type: image }
          - { label: Image secondaire 1, name: secondary1, type: image }
          - { label: Image secondaire 2, name: secondary2, type: image }
      - label: Section À propos
        name: about
        type: object
        fields:
          - { label: Image principale, name: feature, type: image }
      - label: Hébergement
        name: accommodation
        type: object
        fields:
          - { label: Photos intérieur, name: interior, type: image, list: true }
          - { label: Photos extérieur, name: exterior, type: image, list: true }
          - { label: Photos terrasse, name: terrace, type: image, list: true }
      - label: Emplacement
        name: location
        type: object
        fields:
          - { label: Image carte, name: map, type: image }
          - { label: Photo Lascaux, name: lascaux, type: image }
          - { label: Photo Canoë, name: canoeing, type: image }
          - { label: Photo Châteaux, name: castles, type: image }
      - label: Galerie
        name: gallery
        type: object
        list: true
        fields:
          - { label: Image, name: image, type: image }
          - { label: Légende (Français), name: caption_fr, type: string }
          - { label: Légende (Anglais), name: caption_en, type: string }
          - { label: Texte alt (Français), name: alt_fr, type: string }
          - { label: Texte alt (Anglais), name: alt_en, type: string }
